export default [
  {
    type: "function",
    name: "createStakingPool",
    inputs: [
      { name: "allocationPoints", type: "uint256", internalType: "uint256" },
      { name: "lpToken", type: "address", internalType: "contract IERC20" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getPendingStakingRewards",
    inputs: [
      { name: "poolId", type: "uint256", internalType: "uint256" },
      { name: "user", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStakingMultiplier",
    inputs: [
      { name: "from", type: "uint256", internalType: "uint256" },
      { name: "to", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStakingPoolInfo",
    inputs: [{ name: "poolId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct LibStaking.PoolInfo",
        components: [
          { name: "lpToken", type: "address", internalType: "contract IERC20" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "allocationPoints", type: "uint256", internalType: "uint256" },
          { name: "lastRewardBlock", type: "uint256", internalType: "uint256" },
          { name: "accumulatedGovernancePerShare", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStakingPoolsLength",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStakingSettings",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStakingUserInfo",
    inputs: [
      { name: "poolId", type: "uint256", internalType: "uint256" },
      { name: "user", type: "address", internalType: "address" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct LibStaking.UserInfo",
        components: [
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "rewardDebt", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  { type: "function", name: "massUpdateStakingPools", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "setGovernanceBonusEndBlock",
    inputs: [{ name: "newGovernanceBonusEndBlock", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGovernanceBonusMultiplier",
    inputs: [{ name: "newGovernanceBonusMultiplier", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGovernancePerBlock",
    inputs: [{ name: "newGovernancePerBlock", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGovernanceTreasuryDivider",
    inputs: [{ name: "newGovernanceTreasuryDivider", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setStakingRewardToken",
    inputs: [{ name: "newRewardToken", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setStakingStartBlock",
    inputs: [{ name: "newStartBlock", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "stake",
    inputs: [
      { name: "poolId", type: "uint256", internalType: "uint256" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unstake",
    inputs: [
      { name: "poolId", type: "uint256", internalType: "uint256" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateStakingPool",
    inputs: [
      { name: "poolId", type: "uint256", internalType: "uint256" },
      { name: "allocationPoints", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateStakingPool",
    inputs: [{ name: "poolId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;
